locals {
  body = {
    kind = local.arm_kind
    properties = {
      enabled                           = var.enabled
      httpsOnly                         = var.https_only
      serverFarmId                      = var.service_plan_resource_id
      reserved                          = local.is_linux
      autoGeneratedDomainNameLabelScope = var.auto_generated_domain_name_label_scope
      clientAffinityEnabled             = var.client_affinity_enabled
      clientAffinityPartitioningEnabled = var.client_affinity_partitioning_enabled
      clientAffinityProxyEnabled        = var.client_affinity_proxy_enabled
      clientCertEnabled                 = var.client_certificate_enabled
      clientCertMode                    = var.client_certificate_enabled ? var.client_certificate_mode : null
      clientCertExclusionPaths          = var.client_certificate_exclusion_paths
      containerSize                     = var.container_size
      endToEndEncryptionEnabled         = var.end_to_end_encryption_enabled
      hostNamesDisabled                 = var.host_names_disabled
      hyperV                            = var.hyper_v
      ipMode                            = var.ip_mode
      keyVaultReferenceIdentity         = var.key_vault_reference_identity
      managedEnvironmentId              = var.managed_environment_id
      publicNetworkAccess               = var.public_network_access_enabled ? "Enabled" : "Disabled"
      redundancyMode                    = var.redundancy_mode
      scmSiteAlsoStopped                = var.scm_site_also_stopped
      sshEnabled                        = var.ssh_enabled
      storageAccountRequired            = var.storage_account_required
      virtualNetworkSubnetId            = var.virtual_network_subnet_id
      workloadProfileName               = var.workload_profile_name
      siteConfig                        = local.site_config_body
      outboundVnetRouting = {
        allTraffic           = var.vnet_route_all_traffic
        applicationTraffic   = var.vnet_application_traffic_enabled
        backupRestoreTraffic = var.virtual_network_backup_restore_enabled
        contentShareTraffic  = var.vnet_content_share_enabled
        imagePullTraffic     = var.vnet_image_pull_enabled
      }
      daprConfig = var.dapr_config != null ? {
        appId              = var.dapr_config.app_id
        appPort            = var.dapr_config.app_port
        enableApiLogging   = var.dapr_config.enable_api_logging
        enabled            = var.dapr_config.enabled
        httpMaxRequestSize = var.dapr_config.http_max_request_size
        httpReadBufferSize = var.dapr_config.http_read_buffer_size
        logLevel           = var.dapr_config.log_level
      } : null
      dnsConfiguration = var.dns_configuration != null ? {
        alternatePrivateDnsZoneId = var.dns_configuration.alternate_private_dns_zone_id
        dnsLegacySortOrder        = var.dns_configuration.dns_legacy_sort_order
        dnsSuffix                 = var.dns_configuration.dns_suffix
      } : null
      hostingEnvironmentProfile = var.hosting_environment_id != null ? {
        id = var.hosting_environment_id
      } : null
      resourceConfig = var.resource_config != null ? {
        cpu    = var.resource_config.cpu
        memory = var.resource_config.memory
      } : null
      functionAppConfig = var.function_app_uses_fc1 ? {
        deployment = {
          storage = {
            type  = var.storage_container_type
            value = var.storage_container_endpoint
            authentication = {
              type                               = var.storage_authentication_type
              storageAccountConnectionStringName = null
              userAssignedIdentityResourceId     = var.storage_user_assigned_identity_id
            }
          }
        }
        scaleAndConcurrency = {
          alwaysReady          = length(var.always_ready) > 0 ? [for k, v in var.always_ready : { name = coalesce(v.name, k), instanceCount = v.instance_count }] : null
          maximumInstanceCount = var.maximum_instance_count
          instanceMemoryMB     = var.instance_memory_in_mb
        }
        runtime = {
          name    = var.fc1_runtime_name
          version = var.fc1_runtime_version
        }
      } : null
      dailyMemoryTimeQuota = local.is_function_app && !var.function_app_uses_fc1 ? var.daily_memory_time_quota : null
    }
  }
}
