resource "azapi_resource" "this" {
  location  = var.location
  name      = var.name
  parent_id = var.parent_id
  type      = "Microsoft.Web/sites/slots@2025-03-01"
  body = {
    kind = var.kind
    properties = {
      autoGeneratedDomainNameLabelScope = var.auto_generated_domain_name_label_scope
      clientAffinityEnabled             = var.client_affinity_enabled
      clientAffinityPartitioningEnabled = var.client_affinity_partitioning_enabled
      clientAffinityProxyEnabled        = var.client_affinity_proxy_enabled
      clientCertEnabled                 = var.client_certificate_enabled
      clientCertExclusionPaths          = var.client_certificate_exclusion_paths
      clientCertMode                    = var.client_certificate_mode
      containerSize                     = var.container_size
      enabled                           = var.enabled
      endToEndEncryptionEnabled         = var.end_to_end_encryption_enabled
      hostNamesDisabled                 = var.host_names_disabled
      httpsOnly                         = var.https_only
      hyperV                            = var.hyper_v
      ipMode                            = var.ip_mode
      keyVaultReferenceIdentity         = var.key_vault_reference_identity
      managedEnvironmentId              = var.managed_environment_id
      publicNetworkAccess               = var.public_network_access_enabled ? "Enabled" : "Disabled"
      redundancyMode                    = var.redundancy_mode
      scmSiteAlsoStopped                = var.scm_site_also_stopped
      serverFarmId                      = coalesce(var.server_farm_id, var.service_plan_resource_id)
      sshEnabled                        = var.ssh_enabled
      storageAccountRequired            = var.storage_account_required
      virtualNetworkSubnetId            = var.virtual_network_subnet_id
      workloadProfileName               = var.workload_profile_name
      outboundVnetRouting = {
        allTraffic           = var.vnet_route_all_traffic
        applicationTraffic   = var.vnet_application_traffic_enabled
        backupRestoreTraffic = var.vnet_backup_restore_enabled
        contentShareTraffic  = var.vnet_content_share_enabled
        imagePullTraffic     = var.vnet_image_pull_enabled
      }
      siteConfig = var.site_config != null ? {
        alwaysOn                    = var.function_app_uses_fc1 ? null : var.site_config.always_on
        apiDefinition               = var.site_config.api_definition_url != null ? { url = var.site_config.api_definition_url } : null
        apiManagementConfig         = var.site_config.api_management_api_id != null ? { id = var.site_config.api_management_api_id } : null
        appCommandLine              = var.site_config.app_command_line
        autoHealEnabled             = var.site_config.auto_heal_enabled
        autoHealRules               = module.site_config_helpers.auto_heal_rules
        cors                        = local.cors
        defaultDocuments            = var.site_config.default_documents
        detailedErrorLoggingEnabled = var.site_config.detailed_error_logging_enabled
        documentRoot                = var.site_config.document_root
        elasticWebAppScaleLimit     = var.site_config.elastic_web_app_scale_limit
        experiments = var.site_config.experiments != null ? {
          rampUpRules = [for rule in coalesce(var.site_config.experiments.ramp_up_rules, []) : {
            actionHostName            = rule.action_host_name
            changeDecisionCallbackUrl = rule.change_decision_callback_url
            changeIntervalInMinutes   = rule.change_interval_in_minutes
            changeStep                = rule.change_step
            maxReroutePercentage      = rule.max_reroute_percentage
            minReroutePercentage      = rule.min_reroute_percentage
            name                      = rule.name
            reroutePercentage         = rule.reroute_percentage
          }]
        } : null
        ftpsState = var.site_config.ftps_state
        handlerMappings = var.site_config.handler_mappings != null ? [for hm in var.site_config.handler_mappings : {
          arguments       = hm.arguments
          extension       = hm.extension
          scriptProcessor = hm.script_processor
        }] : null
        healthCheckPath                     = var.site_config.health_check_path
        http20Enabled                       = var.site_config.http2_enabled
        http20ProxyFlag                     = var.site_config.http20_proxy_flag
        httpLoggingEnabled                  = var.site_config.http_logging_enabled
        ipSecurityRestrictions              = length(module.site_config_helpers.ip_security_restrictions) > 0 ? module.site_config_helpers.ip_security_restrictions : null
        ipSecurityRestrictionsDefaultAction = var.site_config.ip_restriction_default_action
        limits = var.site_config.limits != null ? {
          maxDiskSizeInMb  = var.site_config.limits.max_disk_size_in_mb
          maxMemoryInMb    = var.site_config.limits.max_memory_in_mb
          maxPercentageCpu = var.site_config.limits.max_percentage_cpu
        } : null
        loadBalancing                          = var.site_config.load_balancing_mode
        localMySqlEnabled                      = var.site_config.local_mysql_enabled
        logsDirectorySizeLimit                 = var.site_config.logs_directory_size_limit
        managedPipelineMode                    = var.site_config.managed_pipeline_mode
        minTlsCipherSuite                      = var.site_config.min_tls_cipher_suite
        minTlsVersion                          = var.site_config.minimum_tls_version
        numberOfWorkers                        = var.site_config.worker_count
        preWarmedInstanceCount                 = var.site_config.pre_warmed_instance_count
        remoteDebuggingEnabled                 = var.site_config.remote_debugging_enabled
        remoteDebuggingVersion                 = var.site_config.remote_debugging_version
        requestTracingEnabled                  = var.site_config.request_tracing_enabled
        requestTracingExpirationTime           = var.site_config.request_tracing_expiration_time
        scmIpSecurityRestrictions              = length(module.site_config_helpers.scm_ip_security_restrictions) > 0 ? module.site_config_helpers.scm_ip_security_restrictions : null
        scmIpSecurityRestrictionsDefaultAction = var.site_config.scm_ip_restriction_default_action
        scmIpSecurityRestrictionsUseMain       = var.site_config.scm_use_main_ip_restriction
        scmMinTlsVersion                       = var.site_config.scm_minimum_tls_version
        scmType                                = var.site_config.scm_type
        tracingOptions                         = var.site_config.tracing_options
        use32BitWorkerProcess                  = var.site_config.use_32_bit_worker
        virtualApplications                    = local.virtual_applications
        vnetPrivatePortsCount                  = var.site_config.vnet_private_ports_count
        vnetRouteAllEnabled                    = var.site_config.vnet_route_all_enabled
        webSocketsEnabled                      = var.site_config.websockets_enabled
        websiteTimeZone                        = var.site_config.website_time_zone
        minimumElasticInstanceCount            = var.site_config.elastic_instance_minimum
        functionsRuntimeScaleMonitoringEnabled = var.is_function_app ? var.site_config.runtime_scale_monitoring_enabled : null
        autoSwapSlotName                       = var.site_config.auto_swap_slot_name
        acrUserManagedIdentityID               = var.site_config.container_registry_managed_identity_client_id
        acrUseManagedIdentityCreds             = var.site_config.container_registry_use_managed_identity
        functionAppScaleLimit                  = var.is_function_app ? var.site_config.app_scale_limit : null
        linuxFxVersion                         = module.site_config_helpers.linux_fx_version
        windowsFxVersion                       = module.site_config_helpers.windows_fx_version
        netFrameworkVersion                    = module.site_config_helpers.net_framework_version
        phpVersion                             = module.site_config_helpers.php_version
        pythonVersion                          = module.site_config_helpers.python_version
        nodeVersion                            = module.site_config_helpers.node_version
        javaVersion                            = module.site_config_helpers.java_version
        javaContainer                          = module.site_config_helpers.java_container
        javaContainerVersion                   = module.site_config_helpers.java_container_version
        powerShellVersion                      = module.site_config_helpers.powershell_version
      } : null
      daprConfig = var.dapr_config != null ? {
        appId              = var.dapr_config.app_id
        appPort            = var.dapr_config.app_port
        enableApiLogging   = var.dapr_config.enable_api_logging
        enabled            = var.dapr_config.enabled
        httpMaxRequestSize = var.dapr_config.http_max_request_size
        httpReadBufferSize = var.dapr_config.http_read_buffer_size
        logLevel           = var.dapr_config.log_level
      } : null
      dnsConfiguration = var.dns_configuration != null ? {
        alternatePrivateDnsZoneId = var.dns_configuration.alternate_private_dns_zone_id
        dnsLegacySortOrder        = var.dns_configuration.dns_legacy_sort_order
        dnsSuffix                 = var.dns_configuration.dns_suffix
      } : null
      hostingEnvironmentProfile = var.hosting_environment_id != null ? {
        id = var.hosting_environment_id
      } : null
      resourceConfig = var.resource_config != null ? {
        cpu    = var.resource_config.cpu
        memory = var.resource_config.memory
      } : null
    }
  }
  response_export_values = [
    "identity.principalId",
  ]
  tags = var.tags

  dynamic "identity" {
    for_each = module.site_config_helpers.has_identity ? [module.site_config_helpers.identity_block] : []

    content {
      type         = identity.value.type
      identity_ids = identity.value.identity_ids
    }
  }
}

# Slot app settings
module "config_appsettings" {
  source = "../config_appsettings"

  app_settings = local.merged_app_settings
  parent_id    = azapi_resource.this.id
  is_slot      = true
}

# Slot connection strings
module "config_connectionstrings" {
  source = "../config_connectionstrings"

  connection_strings = var.connection_strings
  parent_id          = azapi_resource.this.id
  is_slot            = true
}

# Slot storage account mounts
module "config_azurestorageaccounts" {
  source = "../config_azurestorageaccounts"

  parent_id = azapi_resource.this.id
  storage_shares_to_mount = { for k, v in var.storage_shares_to_mount : k => merge(v, {
    access_key = var.storage_shares_access_keys[k]
  }) }
  is_slot = true
}

# Slot FTP publishing credential policy
module "ftp_publishing_credential_policy" {
  source   = "../publishing_credential_policy"
  for_each = !var.ftp_publish_basic_authentication_enabled ? { "default" = {} } : {}

  name      = "ftp"
  parent_id = azapi_resource.this.id
  allow     = false
  is_slot   = true
}

# Slot SCM publishing credential policy
module "scm_publishing_credential_policy" {
  source   = "../publishing_credential_policy"
  for_each = !var.webdeploy_publish_basic_authentication_enabled ? { "default" = {} } : {}

  name      = "scm"
  parent_id = azapi_resource.this.id
  allow     = false
  is_slot   = true
}
