variable "enable_telemetry" {
  type        = bool
  default     = true
  description = <<DESCRIPTION
This variable controls whether or not telemetry is enabled for the module.
For more information see <https://aka.ms/avm/telemetryinfo>.
If it is set to false, then no telemetry will be collected.
DESCRIPTION
}

# ---------------------------------------------------------------------------
# Auth secrets — stored as INPUT VARIABLES, never computed at runtime.
# This is the key pattern that prevents token/credential drift:
#   - Values come from a static source (tfvars, CI/CD secret, Key Vault input)
#   - They are NOT dynamically generated by another resource in this run
# ---------------------------------------------------------------------------

variable "aad_client_id" {
  type        = string
  description = "The Azure AD application (client) ID used for Easy Auth v2."
  sensitive   = false # Client ID is not a secret — safe to store in state
}

variable "aad_client_secret" {
  type        = string
  description = <<DESCRIPTION
The Azure AD client secret value for Easy Auth v2.
DRIFT-SAFE PATTERN: This value is stored in an azurerm_key_vault_secret so
that the App Service app setting references it by KEY NAME, not by value.
The app setting is set to the KEY NAME string ("AAD_CLIENT_SECRET"),
which never changes even when the actual secret is rotated in Key Vault.
DESCRIPTION
  sensitive = true
}

variable "aad_tenant_id" {
  type        = string
  description = "The Azure AD tenant ID for the OpenID issuer URL."
}
